## Ejercicios de Matplotlib

_Resumen previo_ (conceptos que debemos tener claros)

Estamos usando Python 3. Python tiene tipos de datos básicos:

* Int: numérico entero
* Float: numérico decimal
* Complejos: números complejos
* Boolean: booleano (verdadero o falso)
* String: cadena de caracteres


In [1]:
a = 7
b = 7.2
c = 2 + 3j
d = False
e = 'hola, ¿qué tal?'

Con esos datos podemos hacer operaciones. Si son numéricos podemos sumarlos, restarlos, etc., si son booleanos podemos aplicar lógica, si es una cadena de caracteres podemos ver su longitud, cambiarla a mayúsculas, etc.

Pero con estos tipos de datos tenemos UN SOLO valor y no vamos a poder hacer mucho. Python tiene también tipos que son estructuras que almacenan VARIOS valores:

* Secuencias: Los tipos list, tuple y range
* Mapas: El tipo dict
* Conjuntos: El tipo set
* Clases

In [2]:
una_lista = [1, 2, 'fru']
una_tupla = (4, 5, 'ta')
un_range = range(3) # range crea una secuencia, pero no almacena datos en general
un_diccionario = {1: 'hola', 2: 'buenos días', 'día': 8, 'mes': 9}

un_set=set([1,2,3,1,2,3,4,5,1,2,3,1,2]) # guarda 1,2,3,4,5
# los conjuntos no tienen datos repetidos, no se usan para almacenar datos en general

# las clases las repasaremos con Hundir la flota

Para trabajar con VARIOS datos se pueden usar __listas con corchetes, tuplas con paréntesis o diccionarios con llaves__.

* _Una lista es mutable, se pueden cambiar los valores que guarda; índice numérico, valores distintos si quieres._
* _Una tupla es inmutable, NO se pueden cambiar los valores que guarda; índice numérico, valores distintos si quieres._
* _Un diccionario son pares clave-valor. Ahora las claves las defines tú; claves las que quieras, sin orden._

In [3]:
una_lista[0] = 9

valor = una_tupla[0] + 2

for x in un_range:
    print(una_lista[x] + una_tupla[x])
    
claves = un_diccionario.keys()
for clave in claves:
    print(un_diccionario[clave])


13
7
fruta
hola
buenos días
8
9


Tenemos las listas, pero existe la librería numpy que es muy potente con los arrays (arrays de Numpy). Tiene métodos muy buenos.

In [4]:
import numpy as np

print(np.array([1,2,3])) # Construyo un array de numpy pasando una lista
print(np.arange(0,10,4)) # inicio, fin sin cogerlo, paso
print(np.linspace(0,10,4)) # inicio, fin cogiéndolo, número de elementos


[1 2 3]
[0 4 8]
[ 0.          3.33333333  6.66666667 10.        ]


Además de numpy, existe Pandas, una librería para trabajar con DataFrames (filas y columnas, con índices en las filas y nombres de columna en las columnas). Cada columna de un DataFrame es un Series (un array donde el índice puede ser texto).

In [5]:
import pandas as pd

pd.DataFrame(una_lista, columns=['valores'])

valores
0       9
1       2
2     fru

In [6]:
otro_diccionario = {'altura': [160, 170, 180, 190, 160], \
                    'ojos': ['marrones', 'azules', 'marrones', 'marrones', 'verdes']}

pd.DataFrame(otro_diccionario)

altura      ojos
0     160  marrones
1     170    azules
2     180  marrones
3     190  marrones
4     160    verdes

#### Ejercicios de Matplotlib

1. Importa pyplot, numpy y pandas

2. Activa matplotlib de forma estática

3. Sabemos que podemos pintar gráficas de dos formas: la figura incluye los ejes o teniendo figura y ejes por separado.
Usando solo una figura, usa numpy para los valores del eje X entre 0 y 5. Pinta dos gráficas en dos cajas distintas, a la izquierda una recta con pendiente positiva de 3 que pase por (0,0) y a la derecha una recta con pendiente negativa de 3 que pase por (0,-5). Elige la precisión en el eje X que desees.  

4. Fija el eje X entre 0 y 5 y el eje Y entre -15 y 15

5. Llama al eje X "eje X", al eje Y "eje Y" y pon de títulos "recta sube" y "recta baja". Muestra dos etiquetas de ejeX pero solo una de eje Y.

Vamos a pintar lo mismo pero accediendo directamente a los ejes

6. Usando una figura Y EJES POR SEPARADO, usa numpy para los valores del eje X entre 0 y 5. Pinta dos gráficas en dos cajas distintas, a la izquierda una recta con pendiente positiva de 3 que pase por (0,0) y a la derecha una recta con pendiente negativa de 3 que pase por (0,-5). Elige la precisión en el eje X que desees.  

In [7]:
# obtén solo la figura y los ejes y mira el resultado




In [8]:
# basándote en el código previo, cambia solo la manipulación de los ejes
# recuerda que hay unos métodos que su nombre cambia un poco



7. Existen distintos modelos de gráficas.


<img src="modelos_graficas.png" width="200">

Crea una lista de coordenadas X: 20, 22, 24, 26, 28
Crea una lista de coordenadas Y: 5, 15, -5, 20, 5
Usa un gráfico de barras colocadas en X con alturas Y

8. Crea un gráfico de barras. Pintamos la altura de un grupo de amigos, cada barra representa a una persona. Ana mide 160 cm, Luis mide 180 cm, Pedro mide 175 cm, Sofía mide 190 cm, Carmen mide 170 cm. Las barras serán verdes.
Consejo: si no vas a tener que manipular especialmente los ejes, es más sencillo dejarlos dentro de la figura.

9. Basándote en el gráfico anterior, escribe encima de cada barra la altura de cada amigo.
Pista: usa un bucle que lea cada barra de barplot = plt.bar(x,y)
bar tiene los métodos get_height(), get_x(), get_width()
plt.text(x,y,valor, va='bottom')

10. Cambia el tamaño de la figura a (3,5)

11. Basándote en el gráfico anterior, borra la escala del eje Y (ya aparece en la altura)
Pista: cuando plt.yticks() recibe una lista vacía no pinta el eje Y

12. Prueba a hacer el gráfico con las barras en horizontal (no es necesario poner el texto al final de la barra).

13. Prueba a invertir los ejes con ax.invert_axis()
Necesitarás tener los ejes disponibles fuera de la figura

14. En el último gráfico, cambia el estilo a 'dark_background'

15. Vamos a introducir pandas. Crea un DataFrame con las columnas "Year" de valores 2015, 2016, 2017, 2018, 2019 y la columna "Sold_items_A" de valores 1000, 3500, 4000, 5500, 7000

16. Ahora pintamos un gráfico de línea con las ventas respecto al año. Pon un título y etiquetas en los ejes.
Cambia el estilo a 'seaborn-white'. La línea debe ser con rayas y verde.

17. Otro departamento B ha vendido en esos años 2000, 3100, 5000, 4000, 6000 unidades. Incluye esa columna en el DataFrame y pinta en la misma gráfica las dos líneas. B es una línea punteada y roja. Muestra una leyenda abajo a la derecha.

In [9]:
# df

18. Haz un scatter del departamento A usando __solo el DataFrame__.
Pista: el propio DataFrame tiene un método plot.
df.plot('columna X', 'columna Y', 'kind' = 'scatter)

19. Prueba a cambiar kind a 'pie'

20. Prueba a quitar la leyenda incluyendo legend igual a False, añade labels y quita la etiqueta en Y

21. Vamos a pintar un histograma

In [10]:

np.random.seed(1) # cada vez que le pida N números aleatorios, me dará los mismos

mydf = pd.DataFrame({"Altura" : np.random.randint(low=150, high=190, size=300)})

Pista: https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.plot.html

In [11]:
# Histogram



Nota: con ax = df.plot()

se pueden poner las etiquetas con

ax.set(xlabel="Bins")

22. Contornos de 3D a 2D. Escribe una función que recibiendo x,y devuelva (1 - x / 2 + x ** 5 + y ** 3) * np.exp(-x ** 2 -y ** 2)

Tablero: Tanto x como y van de -3 a 3 y usaremos 256 puntos.
Usa contourf, con 8 niveles (cortes), una transparencia de 0.75 y un color map de tipo 'jet'. 
Bonus: pinta las líneas de los contornos también de negro